config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}

  scope :document_analyses, controller: 'analysis', as: 'analyses' do
    get :task_page
    get :search
    post :execute_task
  end

  post '/ajax_api' => 'ajax#multiplex'
  get '/ajax_api' => 'ajax#multiplex'

  resources :notification_logs, only: [:index] do  
    collection do
      get :list
    end
  end
  
  scope :twitter, as: 'twitter', controller: 'twitters' do
    get :authorize_twitter
    get :set_twitter_token    

    get :schedule
    post :schedule
    
    get :index
    get :input_handle
    post :twitter_call
    post :batch_call
    
    get "/analysis(/:handle)", action: :analyze, as: :profile_analysis
    get '/feed(/:handle)', action: :feed, as: :feed
  end
  
  resources 'redirect_maps', path: 'r', only: [:show]
  
  # Admin
  require 'sidekiq/web'
  #authenticate :admin, lambda { |u| u.is_a? Admin } do
  mount Sidekiq::Web => '/sidekiq_ui'
  #end
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  include TwitterAnalysis
  before_action :set_handle_or_return, only: [:twitter_call, :analyze, :feed]
  before_action :authenticate_user!, only: [:schedule]

  def schedule
    # Can only schedule for connected accounts.
    if current_user.twitter_profile.nil?
      flash[:notice] = 'Your account doesn\'t have a handle yet. Please set one.'
      redirect_to twitter_input_handle_path and return
    end
    
    if request.request_method == 'GET'
      render :schedule
    elsif request.request_method == 'POST'
      if message_list = construct_messages
        @app_token = set_app_tokens
        DripTweetJob.perform_later current_user.twitter_profile, message_list, token: @app_token
      end
    else
      redirect_to new_user_session_path
    end
  end
  
  def input_handle
    set_input_handle_path_vars
  end

  def index
    @handles_by_tweets = Tweet.joins(:user).group('twitter_profiles.handle').count

    # Filter down if there's a filter parameter
    leader=nil
    if params[:followers_of]
      leader = TwitterProfile.find_by_handle params[:followers_of]
    end
    if !leader and current_user and current_user.twitter_profile and current_user.twitter_profile.handle
      leader = current_user.twitter_profile
    end
    if leader
      @profiles_list = leader.followers
    else
      @profiles_list = TwitterProfile.where('handle is not null')
    end

    @profiles_list = @profiles_list.joins(:profile_stat).includes(:profile_stat).where('profile_stats.stats_hash_v2 != ?', '{}')
    @profiles_list_sorts = {tweets_count: @profiles_list.order(tweets_count: :desc),
                            tweets_retrieved: @profiles_list.order('(profile_stats.stats_hash_v2 ->> \'total_tweets\')::integer desc'),
                            retweets_collected: @profiles_list.order('(profile_stats.stats_hash_v2 ->> \'retweet_aggregate\')::integer desc'),
                            retweeted_avg: @profiles_list.order('(profile_stats.stats_hash_v2 ->> \'retweeted_avg\')::float desc'),
                            last_known_tweet_time: @profiles_list.order(last_tweet_time: :desc)
                           }
  end

  def authorize_twitter
    if current_user
      client = OAuth::Consumer.new(
        Rails.application.secrets.twitter_consumer_key,
        Rails.application.secrets.twitter_consumer_secret,
        site: 'https://api.twitter.com'
      )

      callback_str = twitter_set_twitter_token_url
      request_token = client.get_request_token(oauth_callback: callback_str)

      o = OauthTokenHash.create(source: 'twitter', user: current_user, request_token: request_token.to_yaml)
      if Rails.env.test?
        redirect_to 'test.twitter.com/authorize'
      else
        redirect_to request_token.authorize_url
      end
    else
      redirect_to new_user_session_path, notice: 'Need to be signed in locally'
    end      
  end
  
  def set_twitter_token
    if current_user
      if params[:oauth_token].present? and
        params[:oauth_verifier].present?
        latest_tokenhash = current_user.latest_token_hash('twitter')

        req_token = YAML.load(latest_tokenhash.request_token)
        client = OAuth::Consumer.new(
          Rails.application.secrets.twitter_consumer_key,
          Rails.application.secrets.twitter_consumer_secret,
          site: 'https://api.twitter.com'
        )

        acc_token = client.get_access_token(req_token, oauth_verifier: params[:oauth_verifier])
        # This token will not expire - https://dev.twitter.com/oauth/overview/faq (9/9/16)
        latest_tokenhash.update_attributes(token: acc_token.token, secret: acc_token.secret)

        x = current_user
        TwitterClientWrapper.new(token: latest_tokenhash).rate_limited('account_settings') do
          account_settings! x
        end

        @remote_id = x.twitter_profile.handle
      else
        render nothing: true
      end
    else
      render nothing: true
    end
  end

  def batch_call
    @app_token = set_app_tokens
    if (by_l_cmd = params.keys.select { |i| i =~ /by\-leader/ }.compact).size > 0
      unless params[:leader_handle].nil? or (leader = TwitterProfile.find_by_handle(params[:leader_handle])).nil?
        case by_l_cmd[0].downcase
        when /bio.*by.*leader/
          leader.process_followers :bios, @app_token
        end
      end
    else
      if params["no-tweet-profiles"].present?
        TwitterProfile.with_no_tweets.all.each do |profile|
          bio profile
          tweets profile
        end
      end
    end
    redirect_to twitter_input_handle_path
  end
  
  def twitter_call
    notice = nil
    actname = params[:action_name]
    if actname && is_valid_batch_command?(actname)
      @app_token = set_app_tokens
      case actname.downcase
      when 'refresh-feed'
        if current_user
          # Can't refresh feed if no one's logged in
          notice = TwitterManagement::Feed.refresh_feed(@bio, @app_token).join '; '
        end
      when 'refresh-friends'
        my_friends
        notice = 'Started friends job'
      when 'populate-followers'
        followers
        notice = 'Started followers job'
      when 'get-bio'
        bio @bio
        notice = 'Started bio refresh job'
      when 'get-older-tweets', 'get-all-older-tweets'
        # Let's get the bio too, if we never did, when asking for tweets
        bio @bio if !@bio.member_since.present?
        notice = 'Started older tweets job'

        pagination = (actname == /get-all-older-tweets/ ? {pagination: true} : {})
        tweets(@bio, ({direction: 'older'}.merge(pagination)))
      when 'get-newer-tweets'
        tweets(@bio, direction: 'newer')
        notice = 'Started newer tweets job'
      end

      flash[:notice] = "Request returned: #{notice}"
      flash[:last_used_handle] = @bio.handle
    else
      flash[:alert] = 'No such action - something went wrong.'
    end
    redirect_to twitter_profile_analysis_path(handle: @bio.handle)
  end

  def feed
    unless params[:refresh_now] == '1' or current_user.nil?
      @time_to_wait = (Time.now - 24.hours) - (Tweet.top_of_feed(current_user.twitter_profile) || DateTime.now - 1.year)

      # how long before the next refresh? Might be more efficient to do this on the client, in JS
      if @time_to_wait < 0
        t = -1 * @time_to_wait
        @hrs = (t / 3600).floor
        @mins = (60 * ((t / 3600) - @hrs)).floor
        @secs = (t - (3600 * @hrs + 60 * @mins)).floor
      end
    else
      @time_to_wait = 0
    end

    page =
      if current_user
        bkmk_key = "#{current_user.email}.twitter.bookmark"
        bkmk = Config.find_by_config_key(bkmk_key)&.config_value
        params[:page]&.to_i || bkmk&.to_i || 1
      else
        1
      end
    
    @feed_list = current_user&.twitter_profile ?
                   Tweet.latest_by_friends(current_user.twitter_profile).paginate(page: page, per_page: 10) :
                   []
    if @feed_list.size > 0 && (params[:page]&.to_i == 1 || bkmk.nil? || bkmk.to_i < page)
      c = Config.find_or_create_by(config_key: bkmk_key)
      c.update_attributes config_value: page
    end
  end
  
  def analyze
    @latest_tweets = Tweet.where(user: @bio).order(tweeted_at: :desc)

    newest_tweet_enter_date = (lt = @latest_tweets&.first) ? lt.tweeted_at : nil
    @been_a_while = lt.nil? || ((DateTime.now - 24.hours) > newest_tweet_enter_date)

    unless @latest_tweets.count == 0
      if @bio.word_cloud.empty? or params[:word_cloud] == '1'
        idlist = @latest_tweets.pluck(:tweet_id)        
        @bio.word_cloud = word_cloud(tweets: TweetText.where({tweet_id: {"$in" => idlist}}),
                                     document_universe: DocumentUniverse.last&.universe, bio: @bio, use_mongo: true)
        @bio.save
      end
      @word_cloud = @bio.word_cloud
    end
    
    @g_set_title = @bio.handle
  end

  private
  def set_input_handle_path_vars
    @no_tweet_profiles_ct = TwitterProfile.with_no_tweets.count
    @user_handle = ''
    
    if current_user&.latest_token_hash
      @user_has_profile = current_user.twitter_profile.present?
      # BUG: this handle might not be set by the account_settings job before this page is refreshed.
      @user_handle = current_user.twitter_profile&.handle
    end
  end
  
  def set_handle_or_return
    # Params overrides other behavior
    if params[:handle].nil? 
      (redirect_to new_user_session_path and return) if (@bio = current_user&.twitter_profile).nil?
    end

    # Set bio if it didn't come from the logged in user above.
    @bio ||= TwitterProfile.where('lower(handle) = ?', "#{params[:handle].strip.downcase}").first
    if @bio.nil? && params[:action_name] == 'get-bio'
      @bio = TwitterProfile.create handle: params[:handle].downcase
    end
    
    (redirect_to new_user_session_path and return) if @bio.nil?

    if @bio.twitter_id.present?
      @identifier_fk_hash = {twitter_id: @bio.twitter_id}
      @identifier = @bio.twitter_id
    else
      @identifier_fk_hash = {handle: @bio.handle}
      @identifier = @bio.handle
    end

    true
  end
  
  def my_friends
    TwitterFetcherJob.perform_later @bio, 'my_friends', token: @app_token
  end
  
  def followers
    TwitterFetcherJob.perform_later @bio, 'followers', token: @app_token, pagination: true
  end
  def bio(t)
    TwitterFetcherJob.perform_later t, 'bio', token: @app_token
  end
  def tweets(t, opts = {})
    Rails.logger.debug ">>> starting tweets job with token #{@app_token}, opts #{opts}"      
    TwitterFetcherJob.perform_later t, 'tweets', ({token: @app_token}.merge(opts))
  end

  def set_app_tokens
    current_user ? current_user.latest_token_hash('twitter') : nil
  end

  def construct_messages
    # return nil if params is incorrect
    ret = nil
    if params[:uri] and (list = params.dig(:twitter_schedule, :messages))
      ret = list.map { |msg| "#{msg} #{params[:uri]}" }
    end

    ret
  end

  def is_valid_batch_command?(action)

app/helpers/twitter_helper.rb
module TwitterHelper
  def number_of_tweets_message(profile)
    # This is only ever called for profiles that have stats calculated
    stat = profile.profile_stat
    "#{sprintf("%0.2f", stat.stats_hash_v2['retweeted_avg'])} / " +
      " #{stat.stats_hash_v2['retweet_aggregate']}"
  end
  
  def nice_date(dt)
    dt.strftime "%Y-%m-%d %H:%M"
  end
  
  def word_display(w, divisor)
    "#{w[0]}: #{sprintf("%0.3g", w[1]*100/divisor)} [#{sprintf("%0.3g", (@word_cloud[:orig_word_explanations][w[0]+'.tf']||1)*100)}, #{sprintf("%0.3g", (@word_cloud[:orig_word_explanations][w[0]+'.idf']||1)*100)}]"
  end
  
  def twitter_cloud_box_partial(type, title_text)
    (word_list, divisor) =
      case type
      when :webdocs
        [@word_cloud[:webdocs_word_cloud], @bio.crawled_web_documents.count]
      when :retweets
        [@word_cloud[:retweets_word_cloud], @word_cloud[:tweets_count] - @word_cloud[:orig_tweets_count]]
      when :all
        [@word_cloud[:all_word_cloud_filtered], @word_cloud[:tweets_count]]
      when :orig
        [@word_cloud[:orig_word_cloud_filtered], @word_cloud[:orig_tweets_count]]
      when :hashtags
        [(@word_cloud[:orig_word_cloud] + @word_cloud[:all_word_cloud]).select { |w| /^\#/.match(w[0])}.sort_by { |p| -p[1]}.uniq { |i| i[0] }, @word_cloud[:tweets_count]]
      when :handles
        [(@word_cloud[:orig_word_cloud] + @word_cloud[:all_word_cloud]).select { |w| /^\@/.match(w[0]) && w[0] != '@'}.sort_by { |p| -p[1]}.uniq { |i| i[0] }, @word_cloud[:tweets_count]]
      end

    render partial: 'twitter_cloud_box',
           locals: {word_list: word_list.slice(0..25),
                    list_type_title: title_text, divisor: divisor}
  end

  def better_urls(tweet)
    if tweet.is_a? Tweet
      mesg_str = tweet.mesg
      entities_hash = tweet.tweet_details['entities']
    else
      # This changed in the Twitter API and I modified it in my code in Sep '16
      mesg_str = tweet['full_text'] || tweet['text']
      entities_hash = tweet['entities']
    end
    
    # Remove t.co urls, and replace with the full extended urls
    str = mesg_str.gsub(/http.?:\/\/t\.co\/[^\s]+/, '')
    unless entities_hash['urls'].nil?
      str += entities_hash['urls'].map do |u|
        unless u['expanded_url'] =~ /twitter.com\//
          "(<a href='#{u['expanded_url']}'>#{u['expanded_url']}</a>)"
        end
      end.join ' '
    end
    
    str.html_safe
  end

  def better_time(tweet)
    tweet.tweeted_at.strftime '%m %d %H:%M'
  end

  def tweet_text(tweet)
    tweet.mesg
  end
end

app/views/twitters/_feed_footer.html.haml
.feed-footer
  Icons made by
  = link_to 'Vaadin/Flaticon', 'http://www.flaticon.com/authors/vaadin'

app/views/twitters/_handle_template.html.haml
.handle
  = link_to (tweet_handle || tweet_id.to_s), 'https://twitter.com/' + (tweet_handle || tweet_id.to_s)

app/views/twitters/_profile_action_buttons.html.haml
#twitter-handle{'data-handle' => handle}
%button#bio.btn.btn-default.dashboard-action{'data-action-name' =>'get-bio'}
  Get bio
%button#older.btn.btn-default.dashboard-action{'data-action-name' =>'get-older-tweets'}
  Get older tweets
%button#newer.btn.btn-default.dashboard-action{'data-action-name' =>'get-newer-tweets'}
  Get newer tweets
%button#followers.btn.btn-default.dashboard-action{'data-action-name' => 'populate-followers'}
  Refresh followers

app/views/twitters/_quote_tweet.html.haml
.line-one
  .handle
    = link_to (quoted_tweet['user']['screen_name'] || quoted_tweet['user']['id_str']), 'https://twitter.com/' + (quoted_tweet['user']['screen_name'] || quoted_tweet['user']['id_str']) 

.mesg
  = (quoted_tweet['full_text'] || quoted_tweet['text'])

app/views/twitters/_reply_svg.html.haml
%svg{version: "1.1", xmlns: "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", x: "0px", y: "0px", style: 'height: 0; width: 0'}
  %defs
    %g#reply
      %path{d: "M496.5,233.842c-30.841-76.706-114.112-115.06-249.823-115.06h-63.953V45.693c0-4.952-1.809-9.235-5.424-12.85 c-3.617-3.617-7.896-5.426-12.847-5.426c-4.952,0-9.235,1.809-12.85,5.426L5.424,179.021C1.809,182.641,0,186.922,0,191.871 c0,4.948,1.809,9.229,5.424,12.847L151.604,350.9c3.619,3.613,7.902,5.428,12.85,5.428c4.947,0,9.229-1.814,12.847-5.428 c3.616-3.614,5.424-7.898,5.424-12.848v-73.094h63.953c18.649,0,35.349,0.568,50.099,1.708c14.749,1.143,29.413,3.189,43.968,6.143 c14.564,2.95,27.224,6.991,37.979,12.135c10.753,5.144,20.794,11.756,30.122,19.842c9.329,8.094,16.943,17.7,22.847,28.839 c5.896,11.136,10.513,24.311,13.846,39.539c3.326,15.229,4.997,32.456,4.997,51.675c0,10.466-0.479,22.176-1.428,35.118	c0,1.137-0.236,3.375-0.715,6.708c-0.473,3.333-0.712,5.852-0.712,7.562c0,2.851,0.808,5.232,2.423,7.136 c1.622,1.902,3.86,2.851,6.714,2.851c3.046,0,5.708-1.615,7.994-4.853c1.328-1.711,2.561-3.806,3.71-6.283 c1.143-2.471,2.43-5.325,3.854-8.562c1.431-3.237,2.43-5.513,2.998-6.848c24.17-54.238,36.258-97.158,36.258-128.756 C511.63,291.039,506.589,259.344,496.5,233.842z", viewBox: "0 0 511.63 511.631"}

app/views/twitters/_stat_boxes.html.haml
- @profiles_list_sorts[sort_method].all.each do |rec|
  .row.handle-details
    .col-xs-2
      = link_to rec.handle, twitter_profile_analysis_path(handle: rec.handle)
    .col-xs-2
      = "#{rec.tweets_count}"
    .col-xs-5
      = number_of_tweets_message(rec)
    .col-xs-3.time-font
      = "#{rec.last_tweet_time.try(:strftime, '%d/%b/%Y %H:%M:%S')}"  
    

app/views/twitters/_twitter_cloud_box.html.haml
.twitter-box.row
  .twitter-box-title
    = "#{list_type_title} (#{divisor})"
  .paragraph
    - word_list.each do |w|
      .twitter-wcbox
        #{word_display w, divisor}

app/views/twitters/analyze.html.haml
.paragraph
  If you don't see the data you expected, try #{link_to('refreshing this page', twitter_profile_analysis_path(handle: @bio.handle, word_cloud: 1))}.

%p
  - if @bio
    .twitter-box.row
      .twitter-biobox.handlebox
        = link_to @bio.handle, "https://www.twitter.com/#{@bio.handle}", target: '_blank'
      .twitter-biobox
        Location: #{@bio.location}
      .twitter-biobox
        #{@bio.bio}
      .twitter-biobox
        Num. followers: #{@bio.num_followers}
    = form_tag twitter_twitter_call_path, class: 'inline-block' do
      = hidden_field_tag :action_name, ''
      = hidden_field_tag :handle, @bio.handle
      = render partial: 'profile_action_buttons', locals: {handle: @bio.handle}
    - if @latest_tweets && @latest_tweets.count > 0
      .paragraph
        #{@latest_tweets.count} tweets retrieved (from&nbsp;
        %b><
          #{nice_date(@latest_tweets.first.tweeted_at)} to #{nice_date(@latest_tweets.last.tweeted_at)}
        ) Retweet Percentage #{sprintf("%0g", 100-@word_cloud[:orig_tweets_count]*100.0/@word_cloud[:tweets_count])}
      - if @universe_size != 0
        = twitter_cloud_box_partial(:retweets, 'Re-Tweets')
        = twitter_cloud_box_partial(:orig, 'Original Tweets')
        = twitter_cloud_box_partial(:webdocs, 'Web Documents')
        = twitter_cloud_box_partial(:hashtags, 'Hashtags')
        = twitter_cloud_box_partial(:handles, 'Handles')
      - else
        No universe was calculated. Go to
        = link_to 'Site Tasks', analyses_task_page_path
        to create one.

app/views/twitters/feed.html.haml
= render 'reply_svg'
.overlay-grayout
  .overlay
    .row
      .x-box
        X
    .row.blownup-image
      .col-xs-12
        .image-container
          %img.img-responsive{src: ''}
        
    .retweet-ui
      .row.quote-entry
        .col-xs-12
          #quote-entry{"aria-labelledby" => "-label", contenteditable: true, spellcheck: true, role: "textbox", "aria-multiline" => true, dir: "ltr", "faria-autocomplete" => "list", "aria-expanded" => false}
      .row.original-tweet
        .action-button#retweet.action{'data-action-id' => 2}
          Retweet

- if @feed_list.size == 0 || @time_to_wait >= 0
  .paragraph
    .btn.feed-refresh.action{'data-action-id' => 1}
      Refresh Feed
- else
  .time_data{'data-hrs' => @hrs, 'data-mins' => @mins, 'data-secs' => @secs}
  .countdown
    .hrs
    .mins
    .secs
- if @feed_list.size > 0
  %ol.tweet-list
    - @feed_list.each do |tweet|
      %ul.item{id: "tweet-#{tweet.tweet_id}", 'data-action-data' => tweet.tweet_id, 'data-overlay-div-class' => 'retweet-ui', "data-handle" => tweet.user.handle}
        .line-one
          = render partial: 'handle_template', locals: {tweet_handle: tweet.user.handle, tweet_id: tweet.user.twitter_id}
          .time
            = better_time(tweet)
          .action-button.nonicon#retweet-dialog
            %svg
              %use{x: '0', y: '0', "xlink:href" => '#reply', transform: 'scale(.04)'}
          .action-button.arrow-right.icon#goto-orig
        - if tweet.is_retweeted
          - rt_handle = (tweet.tweet_details['retweeted_status']['user']['screen_name'] || tweet.tweet_details['entities']['user_mentions'][0]['screen_name'])
          .line-one
            = precede "\u21b3" do
              = render partial: 'handle_template', locals: {tweet_handle: rt_handle, tweet_id: nil}

            .time
              = better_time(tweet)
          .mesg
            = better_urls(tweet.tweet_details['retweeted_status'])
          - if tweet.tweet_details['retweeted_status']['entities']['media']&.size.try(:>, 0)
            .tweet-media
              %img{src: tweet.tweet_details['retweeted_status']['entities']['media'][0]['media_url_https'], 'data-overlay-div-class' => 'blownup-image'}
          - if tweet.tweet_details['retweeted_status']['quoted_status'].present?
            .quoted-mesg
              .line-one
                .handle
                  = tweet.tweet_details['retweeted_status']['quoted_status']['user']['screen_name']
              .line-two
                .mesg
                  = better_urls(tweet.tweet_details['retweeted_status']['quoted_status'])
        - elsif tweet.tweet_details['quoted_status']
          .mesg
            = tweet_text(tweet)
          .quoted_box
            = render partial: 'quote_tweet', locals: {quoted_tweet: tweet.tweet_details['quoted_status']}
        - else
          .mesg
            = better_urls(tweet)
          - if tweet.has_media?
            .tweet-media
              %img{src: tweet.tweet_details['entities']['media'][0]['media_url_https'], 'data-overlay-div-class' => 'blownup-image'}

- if @feed_list.size > 0
  = will_paginate @feed_list, page_links: false
= render 'feed_footer'

app/views/twitters/index.html.haml
%h3
  = "Sort#{current_user ? ' Your Followers': ''} By"
.paragraph.small-font
  (empty? Try populating your followers, or #{link_to "running a stats update", analyses_task_page_url})
.paragraph.row
  .col-xs-12
    .selection-box{'data-target' => 2}
      Time of latest tweet
    .selection-box.sort-target{'data-target' => 1}
      Total tweets
    .selection-box{'data-target' => 0}
      Tweets retrieved
    .selection-box{'data-target' => 3}
      Avg Re-tweets

.profile-list
  .row
    .col-xs-2
      Handle
    .col-xs-2
      Total tweets
    .col-xs-5
      Retweet Stats (avg/total)
    .col-xs-3
      Last tweet at 
  - if @profiles_list.count > 0
    .databox#databox-1
      .paragraph
        = render partial: 'stat_boxes', locals: {sort_method: :tweets_count}

    .databox#databox-0
      .paragraph
        = render partial: 'stat_boxes', locals: {sort_method: :tweets_retrieved}

    .databox#databox-2
      .paragraph
        = render partial: 'stat_boxes', locals: {sort_method: :last_known_tweet_time}

    .databox#databox-3
      .paragraph
        = render partial: 'stat_boxes', locals: {sort_method: :retweeted_avg}

app/views/twitters/input_handle.html.haml
- if @notice
  .paragraph.bottomborder
    = @notice
    
= form_tag twitter_twitter_call_path, id: 'dashboard-form-1' do
  = hidden_field_tag :action_name, ''
  
  .paragraph.dashboard-section
    .dashboard-title
      Fetch Data
    = text_field_tag :handle, (flash[:last_used_handle] || @user_handle), autofocus: true, id: 'twitter-handle', class: 'form-control'
    .analysis-link
      %a{href: ''}
    = render partial: 'profile_action_buttons', locals: {handle: flash[:last_used_handle] || @user_handle}
  - if current_user    
    .paragraph.dashboard-section
      .dashboard-title
        Your Profile
      - if @user_has_profile
        %button.btn.btn-default.dashboard-action{'data-action-name' => 'refresh-friends'}
          Refresh whom you follow
        %button.btn.btn-default.dashboard-action{'data-action-name' => 'refresh-feed'}
          Refresh your feed
      - else
        You haven't registered your Twitter handle yet.
        = link_to "Authorize with Twitter", twitter_authorize_twitter_url
        to do so.

.paragraph.dashboard-section
  .dashboard-title
    Power Users
  = form_tag twitter_batch_call_path do
    %ol.paragraph
      %li
        = link_to "Search your biotags", analyses_search_path
      - if @no_tweet_profiles_ct != 0
        %li.tooltipper
          = "#{@no_tweet_profiles_ct} profiles do not have tweets"
          %span.mesg-box
            Profiles with no tweets created in our db last week OR have been a Twitter member for less than 6 months.
          = submit_tag "Process all!", name: 'no-tweet-profiles', class: 'btn btn-default', id: 'no-tweet-profiles'
      %li
        Process by leader:
        = text_field_tag :leader_handle, @user_handle, class: 'form-control mini-textfield'
        = submit_tag 'Get bios', name: 'bio-by-leader', class: 'btn btn-default'
        = submit_tag 'Get tweets', name: 'tweets-by-leader', class: 'btn btn-default'
        = submit_tag 'Get both', name: 'all-by-leader', class: 'btn btn-default'

app/views/twitters/schedule.html.haml
%h1
  Schedule Repeated Tweeting
= form_tag '/schedule', method: :post do
  = text_field_tag :uri, '', placeholder: 'URI to tweet about'
  #message-list
  #add-message
    Add a message
  = submit_tag 'Schedule!', id: 'schedule-submit'
    
%script#message-template{type:'text/template'}
  %input{name: 'twitter_schedule[messages][]', id: 'message-text', type: 'text', value: '<%- message %>'.html_safe}
  .x-box
    X

app/views/twitters/set_twitter_token.html.haml
Twitter token confirmed. This will be used for future API requests. Your Twitter handle is #{@remote_id}