config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}

  scope :document_analyses, controller: 'analysis', as: 'analyses' do
    get :task_page
    get :search
    post :execute_task
  end

  post '/ajax_api' => 'ajax#multiplex'
  get '/ajax_api' => 'ajax#multiplex'

  resources :notification_logs, only: [:index] do  
    collection do
      get :list
    end
  end
  
  scope :twitter, as: 'twitter', controller: 'twitters' do
    get :authorize_twitter
    get :set_twitter_token    

    get :schedule
    post :schedule
    
    get :index
    get :input_handle
    post :twitter_call
    post :batch_call
    
    get "/analysis(/:handle)", action: :analyze, as: :profile_analysis
    get '/feed(/:handle)', action: :feed, as: :feed
  end
  
  resources 'redirect_maps', path: 'r', only: [:show]
  
  # Admin
  require 'sidekiq/web'
  #authenticate :admin, lambda { |u| u.is_a? Admin } do
  mount Sidekiq::Web => '/sidekiq_ui'
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || twitter_input_handle_path
  end
  def after_sign_out_path_for(resource)
    stored_location_for(resource) || twitter_input_handle_path
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{type: "button", "data-toggle" => "collapse", "data-target" => "#bs-example-navbar-collapse-1"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/"} 
        = t(:site_brand)
    .collapse.navbar-collapse{id: "bs-example-navbar-collapse-1"}
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Index page", twitter_index_url
        %li
          = link_to "Enter handle", twitter_input_handle_url
        - if current_user
          %li.dropdown 
            %a.dropdown-toggle{href: "#", "data-toggle" => "dropdown"} 
              #{current_user.email[0..12]}...
            %b.caret
            %ul.dropdown-menu
              %li
                - if current_user.twitter_profile
                  = link_to 'Profile', twitter_profile_analysis_path
              %li
                = link_to "Feed", twitter_feed_path
              %li
                = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Sign In', new_user_session_path

app/views/application/blank_page.html.haml
This is a catch-all Rails application.